on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir .nyc_output
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test test/commands/create/**/*.test.ts
      - run: npm test test/commands/list/**/*.test.ts
      - run: npm test test/commands/run/**/*.test.ts
      - run: npm test test/commands/*.test.ts
      - run: npm run test-unit

