on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      revision:
        description: 'Branch name or commit hash'
        required: true
        default: 'main'
jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: deb
          os: ubuntu-latest
          artifact_name: ./dist/deb/*
        - target: exe
          os: windows-latest
          artifact_name: ./dist/win/*
        - target: pkg
          os: macos-latest
          artifact_glob: ./dist/macos/*
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install makensis
          fi
      - run: npx oclif pack ${{ matrix.target }} -r .
      - name: Attach artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_glob }}
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
